/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MutualFundsRouteImport } from './routes/mutual-funds'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CibilRouteImport } from './routes/cibil'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as BankingRouteImport } from './routes/banking'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmTasksRouteImport } from './routes/crm.tasks'
import { Route as CrmReportsRouteImport } from './routes/crm.reports'
import { Route as CrmMutualFundsRouteImport } from './routes/crm.mutual-funds'
import { Route as CrmLoginRouteImport } from './routes/crm.login'
import { Route as CrmLoansRouteImport } from './routes/crm.loans'
import { Route as CrmLeadsRouteImport } from './routes/crm.leads'
import { Route as CrmInsuranceRouteImport } from './routes/crm.insurance'
import { Route as CrmCustomersRouteImport } from './routes/crm.customers'
import { Route as BlogsSipGuideRouteImport } from './routes/blogs/sip-guide'
import { Route as BlogsHomeLoanGuideRouteImport } from './routes/blogs/home-loan-guide'
import { Route as BlogsCibilScoreRouteImport } from './routes/blogs/cibil-score'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'

const MutualFundsRoute = MutualFundsRouteImport.update({
  id: '/mutual-funds',
  path: '/mutual-funds',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CibilRoute = CibilRouteImport.update({
  id: '/cibil',
  path: '/cibil',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingRoute = BankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmTasksRoute = CrmTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CrmRoute,
} as any)
const CrmReportsRoute = CrmReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => CrmRoute,
} as any)
const CrmMutualFundsRoute = CrmMutualFundsRouteImport.update({
  id: '/mutual-funds',
  path: '/mutual-funds',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLoginRoute = CrmLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLoansRoute = CrmLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => CrmRoute,
} as any)
const CrmInsuranceRoute = CrmInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCustomersRoute = CrmCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => CrmRoute,
} as any)
const BlogsSipGuideRoute = BlogsSipGuideRouteImport.update({
  id: '/sip-guide',
  path: '/sip-guide',
  getParentRoute: () => BlogsRoute,
} as any)
const BlogsHomeLoanGuideRoute = BlogsHomeLoanGuideRouteImport.update({
  id: '/home-loan-guide',
  path: '/home-loan-guide',
  getParentRoute: () => BlogsRoute,
} as any)
const BlogsCibilScoreRoute = BlogsCibilScoreRouteImport.update({
  id: '/cibil-score',
  path: '/cibil-score',
  getParentRoute: () => BlogsRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/banking': typeof BankingRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/cibil': typeof CibilRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/insurance': typeof InsuranceRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/mutual-funds': typeof MutualFundsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blogs/cibil-score': typeof BlogsCibilScoreRoute
  '/blogs/home-loan-guide': typeof BlogsHomeLoanGuideRoute
  '/blogs/sip-guide': typeof BlogsSipGuideRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/crm/insurance': typeof CrmInsuranceRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/loans': typeof CrmLoansRoute
  '/crm/login': typeof CrmLoginRoute
  '/crm/mutual-funds': typeof CrmMutualFundsRoute
  '/crm/reports': typeof CrmReportsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/banking': typeof BankingRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/cibil': typeof CibilRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/insurance': typeof InsuranceRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/mutual-funds': typeof MutualFundsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blogs/cibil-score': typeof BlogsCibilScoreRoute
  '/blogs/home-loan-guide': typeof BlogsHomeLoanGuideRoute
  '/blogs/sip-guide': typeof BlogsSipGuideRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/crm/insurance': typeof CrmInsuranceRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/loans': typeof CrmLoansRoute
  '/crm/login': typeof CrmLoginRoute
  '/crm/mutual-funds': typeof CrmMutualFundsRoute
  '/crm/reports': typeof CrmReportsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/crm': typeof CrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/banking': typeof BankingRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/cibil': typeof CibilRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/insurance': typeof InsuranceRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/mutual-funds': typeof MutualFundsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blogs/cibil-score': typeof BlogsCibilScoreRoute
  '/blogs/home-loan-guide': typeof BlogsHomeLoanGuideRoute
  '/blogs/sip-guide': typeof BlogsSipGuideRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/crm/insurance': typeof CrmInsuranceRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/loans': typeof CrmLoansRoute
  '/crm/login': typeof CrmLoginRoute
  '/crm/mutual-funds': typeof CrmMutualFundsRoute
  '/crm/reports': typeof CrmReportsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/banking'
    | '/blogs'
    | '/cibil'
    | '/contact'
    | '/crm'
    | '/dashboard'
    | '/insurance'
    | '/loans'
    | '/login'
    | '/mutual-funds'
    | '/admin/employees'
    | '/admin/whatsapp'
    | '/blogs/cibil-score'
    | '/blogs/home-loan-guide'
    | '/blogs/sip-guide'
    | '/crm/customers'
    | '/crm/insurance'
    | '/crm/leads'
    | '/crm/loans'
    | '/crm/login'
    | '/crm/mutual-funds'
    | '/crm/reports'
    | '/crm/tasks'
    | '/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/banking'
    | '/blogs'
    | '/cibil'
    | '/contact'
    | '/dashboard'
    | '/insurance'
    | '/loans'
    | '/login'
    | '/mutual-funds'
    | '/admin/employees'
    | '/admin/whatsapp'
    | '/blogs/cibil-score'
    | '/blogs/home-loan-guide'
    | '/blogs/sip-guide'
    | '/crm/customers'
    | '/crm/insurance'
    | '/crm/leads'
    | '/crm/loans'
    | '/crm/login'
    | '/crm/mutual-funds'
    | '/crm/reports'
    | '/crm/tasks'
    | '/crm'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/banking'
    | '/blogs'
    | '/cibil'
    | '/contact'
    | '/crm'
    | '/dashboard'
    | '/insurance'
    | '/loans'
    | '/login'
    | '/mutual-funds'
    | '/admin/employees'
    | '/admin/whatsapp'
    | '/blogs/cibil-score'
    | '/blogs/home-loan-guide'
    | '/blogs/sip-guide'
    | '/crm/customers'
    | '/crm/insurance'
    | '/crm/leads'
    | '/crm/loans'
    | '/crm/login'
    | '/crm/mutual-funds'
    | '/crm/reports'
    | '/crm/tasks'
    | '/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BankingRoute: typeof BankingRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  CibilRoute: typeof CibilRoute
  ContactRoute: typeof ContactRoute
  CrmRoute: typeof CrmRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  InsuranceRoute: typeof InsuranceRoute
  LoansRoute: typeof LoansRoute
  LoginRoute: typeof LoginRoute
  MutualFundsRoute: typeof MutualFundsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mutual-funds': {
      id: '/mutual-funds'
      path: '/mutual-funds'
      fullPath: '/mutual-funds'
      preLoaderRoute: typeof MutualFundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cibil': {
      id: '/cibil'
      path: '/cibil'
      fullPath: '/cibil'
      preLoaderRoute: typeof CibilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking': {
      id: '/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof BankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/tasks': {
      id: '/crm/tasks'
      path: '/tasks'
      fullPath: '/crm/tasks'
      preLoaderRoute: typeof CrmTasksRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/reports': {
      id: '/crm/reports'
      path: '/reports'
      fullPath: '/crm/reports'
      preLoaderRoute: typeof CrmReportsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/mutual-funds': {
      id: '/crm/mutual-funds'
      path: '/mutual-funds'
      fullPath: '/crm/mutual-funds'
      preLoaderRoute: typeof CrmMutualFundsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/login': {
      id: '/crm/login'
      path: '/login'
      fullPath: '/crm/login'
      preLoaderRoute: typeof CrmLoginRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/loans': {
      id: '/crm/loans'
      path: '/loans'
      fullPath: '/crm/loans'
      preLoaderRoute: typeof CrmLoansRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/insurance': {
      id: '/crm/insurance'
      path: '/insurance'
      fullPath: '/crm/insurance'
      preLoaderRoute: typeof CrmInsuranceRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/customers': {
      id: '/crm/customers'
      path: '/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof CrmCustomersRouteImport
      parentRoute: typeof CrmRoute
    }
    '/blogs/sip-guide': {
      id: '/blogs/sip-guide'
      path: '/sip-guide'
      fullPath: '/blogs/sip-guide'
      preLoaderRoute: typeof BlogsSipGuideRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/home-loan-guide': {
      id: '/blogs/home-loan-guide'
      path: '/home-loan-guide'
      fullPath: '/blogs/home-loan-guide'
      preLoaderRoute: typeof BlogsHomeLoanGuideRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/cibil-score': {
      id: '/blogs/cibil-score'
      path: '/cibil-score'
      fullPath: '/blogs/cibil-score'
      preLoaderRoute: typeof BlogsCibilScoreRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogsRouteChildren {
  BlogsCibilScoreRoute: typeof BlogsCibilScoreRoute
  BlogsHomeLoanGuideRoute: typeof BlogsHomeLoanGuideRoute
  BlogsSipGuideRoute: typeof BlogsSipGuideRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsCibilScoreRoute: BlogsCibilScoreRoute,
  BlogsHomeLoanGuideRoute: BlogsHomeLoanGuideRoute,
  BlogsSipGuideRoute: BlogsSipGuideRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface CrmRouteChildren {
  CrmCustomersRoute: typeof CrmCustomersRoute
  CrmInsuranceRoute: typeof CrmInsuranceRoute
  CrmLeadsRoute: typeof CrmLeadsRoute
  CrmLoansRoute: typeof CrmLoansRoute
  CrmLoginRoute: typeof CrmLoginRoute
  CrmMutualFundsRoute: typeof CrmMutualFundsRoute
  CrmReportsRoute: typeof CrmReportsRoute
  CrmTasksRoute: typeof CrmTasksRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmCustomersRoute: CrmCustomersRoute,
  CrmInsuranceRoute: CrmInsuranceRoute,
  CrmLeadsRoute: CrmLeadsRoute,
  CrmLoansRoute: CrmLoansRoute,
  CrmLoginRoute: CrmLoginRoute,
  CrmMutualFundsRoute: CrmMutualFundsRoute,
  CrmReportsRoute: CrmReportsRoute,
  CrmTasksRoute: CrmTasksRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BankingRoute: BankingRoute,
  BlogsRoute: BlogsRouteWithChildren,
  CibilRoute: CibilRoute,
  ContactRoute: ContactRoute,
  CrmRoute: CrmRouteWithChildren,
  DashboardRoute: DashboardRoute,
  InsuranceRoute: InsuranceRoute,
  LoansRoute: LoansRoute,
  LoginRoute: LoginRoute,
  MutualFundsRoute: MutualFundsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
