
ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS cibil_score INT,
  ADD COLUMN IF NOT EXISTS loan_type TEXT,
  ADD COLUMN IF NOT EXISTS loan_sub_type TEXT,
  ADD COLUMN IF NOT EXISTS loan_amount NUMERIC;

ALTER TABLE public.customers
  ADD COLUMN IF NOT EXISTS loan_type TEXT,
  ADD COLUMN IF NOT EXISTS loan_sub_type TEXT,
  ADD COLUMN IF NOT EXISTS loan_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS cibil_score INT,
  ADD COLUMN IF NOT EXISTS stage TEXT NOT NULL DEFAULT 'New';
